// // employeesData.ts
// import { Timestamp } from "firebase/firestore";

// export const employeesData = [
//   {
//     name: "Phạm Thị Dung",
//     position: "UI/UX Designer",
//     email: "d.pham@company.com",
//     status: "Hoạt động",
//     role: "Nhân viên",
//     img: "https://i.pravatar.cc/150?img=4",
//     createdAt: Timestamp.now(),
//     updatedAt: Timestamp.now(),
//   },
//   {
//     name: "Hoàng Minh Đức",
//     position: "DevOps Engineer",
//     email: "duc.hoang@company.com",
//     status: "Đang onsite",
//     role: "Nhân viên",
//     img: "https://i.pravatar.cc/150?img=5",
//     createdAt: Timestamp.now(),
//     updatedAt: Timestamp.now(),
//   },
//   {
//     name: "Vũ Thị Hạnh",
//     position: "Data Analyst",
//     email: "hanh.vu@company.com",
//     status: "Hoạt động",
//     role: "Nhân viên",
//     img: "https://i.pravatar.cc/150?img=6",
//     createdAt: Timestamp.now(),
//     updatedAt: Timestamp.now(),
//   },
//   {
//     name: "Đinh Văn Long",
//     position: "Scrum Master",
//     email: "long.dinh@company.com",
//     status: "Nghỉ việc",
//     role: "Nhân viên",
//     img: "https://i.pravatar.cc/150?img=7",
//     createdAt: Timestamp.now(),
//     updatedAt: Timestamp.now(),
//   },
//   {
//     name: "Ngô Quỳnh Trang",
//     position: "Product Manager",
//     email: "trang.ngo@company.com",
//     status: "Hoạt động",
//     role: "Quản lý",
//     img: "https://i.pravatar.cc/150?img=8",
//     createdAt: Timestamp.now(),
//     updatedAt: Timestamp.now(),
//   },
//   {
//     name: "Trịnh Hoàng Tú",
//     position: "Mobile Developer",
//     email: "tu.trinh@company.com",
//     status: "Đang nghỉ phép",
//     role: "Nhân viên",
//     img: "https://i.pravatar.cc/150?img=9",
//     createdAt: Timestamp.now(),
//     updatedAt: Timestamp.now(),
//   },
//   {
//     name: "Lâm Thị Thu",
//     position: "Tester",
//     email: "thu.lam@company.com",
//     status: "Hoạt động",
//     role: "Nhân viên",
//     img: "https://i.pravatar.cc/150?img=10",
//     createdAt: Timestamp.now(),
//     updatedAt: Timestamp.now(),
//   },
//   {
//     name: "Phan Anh Tú",
//     position: "Security Engineer",
//     email: "tuphan@company.com",
//     status: "Hoạt động",
//     role: "Nhân viên",
//     img: "https://i.pravatar.cc/150?img=11",
//     createdAt: Timestamp.now(),
//     updatedAt: Timestamp.now(),
//   },
//   {
//     name: "Bùi Thị Mai",
//     position: "HR Manager",
//     email: "mai.bui@company.com",
//     status: "Hoạt động",
//     role: "Quản lý",
//     img: "https://i.pravatar.cc/150?img=12",
//     createdAt: Timestamp.now(),
//     updatedAt: Timestamp.now(),
//   },
//   // 👉 Thêm bao nhiêu tùy ý
// ];
